### ISSUE TITLE
Fork foundation Templates

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#32]
- [x] fork https://github.com/zurb/foundation-apps-template and update to latest version
- [x] add section to docs for how to use the template
- [x] migrate to angular-base-apps 2.0 prerelease
- [x] integrate angular-dynamic-routing
- [x] integrate base-apps-router
  - [x] once [this PR](https://github.com/base-apps/angular-front-router/pull/1) is merged, the dynamic routing build step will be capable of running outside of gulp.
- [x] integrate angular-icons

**Comment by tolyo** [comment]
@soumak77 Do we need the cli? I don't see the point of it. I will get around the template ASAP.

**Comment by soumak77** [comment]
@tolyo whatever steps the CLI performs we can just add to the documentation

**Comment by tolyo** [comment]
@soumak77 We have two npm repoes right now. Please unpublish the unused one.

**Comment by soumak77** [comment]
@tolyo I tried but the command failed.  I opened an issue on npm: https://github.com/npm/npm/issues/13632

**Comment by tolyo** [comment]
@soumak77 Roger

**Comment by soumak77** [comment]
@tolyo what is the reason for replacing `gulp` with `brunch` in the template?  Is it just a preference thing or is there a technical reason?

To accommodate all developers, we can create the same template with different build tools.  I personally would want to have a gulp build when using the template.  The gulp build should also be the default template since the framework uses gulp.

Also, the dynamic routing plugin is built with gulp, so I'm not sure if that will have issues running with brunch.

**Comment by soumak77** [comment]
duplicate npm package has been removed

**Comment by tolyo** [comment]
@soumak77 Because it takes more code in `gulp` to set up ES6 based project with NPM for dependency management. I am assuming that most projects nowadays are started with ES6 and without Bower.

**Comment by soumak77** [comment]
@tolyo understood and I like that direction, but I still think a separate gulp template should be created so that users have options.  I personally have never heard of brunch, so if I was new to this framework, I wouldn't like having to learn a separate build system on top of the framework itself.

**Comment by tolyo** [comment]
@soumak77 This is a sample to try the framework with sensible and modern defaults and not a reference on how the framework should be used. Feel free to replace it with Gulp or Grunt, but the previous version of the template is legacy.

**Comment by soumak77** [comment]
@tolyo I agree I'm looking at it from the standpoint of today versus the future.  Once https://github.com/base-apps/angular-base-apps/issues/42 has been completed, gulp won't be a hard dependency for the framework, so it won't matter at that point.

**Comment by tolyo** [comment]
@soumak77 This isn't close to being done. I want to add sample apps to this: a) a chat app b) a dashboard app and c) task management app

**Comment by soumak77** [comment]
@tolyo looking forward to it!  We can use github pages to host the apps like we do with the docs.  I integrated https://www.npmjs.com/package/gh-pages into the framework build to auto-publish the docs.

**Comment by tolyo** [comment]
@soumak77 I've been looking around for a solid Gulp ES6 stack and they all use Webpack. So it would require an introduction of yet another tool.

**Comment by soumak77** [comment]
@tolyo On an enterprise scale, the build systems can get pretty complex and I would like to have a template that understands this and makes it easy to build scalable apps from the start.  At the same time, I don't want too complex of a build that new comers are off put by using the framework just to hack something together.

Not sure if that helps, but that's my thinking.  If trying to make the base template requires too much upfront knowledge, we can maybe split the template into basic and enterprise versions.

**Comment by tolyo** [comment]
@soumak77 Shooting just for minimal code for now.

**Comment by soumak77** [comment]
@tolyo sounds good.  I want to have a template available for the 2.0 release, so let me know when you get it working for 1.x and I can migrate it to 2.x.

**Comment by tolyo** [comment]
@soumak77 Its functional. Please give it a try.

**Comment by tunecino** [comment]
I like the idea of 2 templates. Yii2 which is a PHP framework introduced 2 templates, and it worked as it allowed introducing all solid stuff and complex architecture via an **advanced** one while also maintaining a **basic** version not only for newcomers but also for small projects with less requirements. 

the **basic** template in this case may use the built-in **front-router** which is great for small projects or non-angular developers while in a future we may also have an **advanced** one using **ui-router** instead, webpack, ... and a component based architecture maybe a little bit like [this](https://github.com/tunecino/Yii2_foundation-apps/tree/master/client/app/image) structure.

**Comment by soumak77** [comment]
@tolyo I'm getting the following errors

```
13 Aug 04:24:16 - warn: Loading of html-pages-brunch failed due to Cannot find module 'mkdirp'
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
13 Aug 04:24:16 - error: Initialization error -  Cannot read property 'brunchPluginName' of null 
Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
```

Also, I think jquery should be removed as a dependency as angular provides the required functionality via jqlite.

**Comment by tolyo** [comment]
@soumak77 OS?

**Comment by tolyo** [comment]
@soumak77 Plz try again w clean install

**Comment by soumak77** [comment]
@tolyo it's working now

**Comment by soumak77** [comment]
@tolyo I just published a prerelease for 2.0 so that we can get the template working with that version.  The prerelease is https://github.com/base-apps/angular-base-apps/releases/tag/v1.2.7-0.

**Comment by soumak77** [comment]
I got the angular base apps docs updated to work with angular-icons, but couldn't figure out how to get the brunch build updated for the templates.  Since the iconic source fails on the import command, it'll likely need to be included outside of app.js.

The new `angular-dynamic-routing` and `angular-icons` modules should be refactored a bit so that they are ES6 compliant (i.e. work well with import).

**Comment by soumak77** [comment]
I updated the template to work with angular-icons v1.0

**Comment by soumak77** [comment]
@tolyo all prerequisites for the template are now completed.  Could you look into hooking up the `base-apps-router` module to run with the template build?  I'm not sure what the proper config is to get a pre-build step to run in brunch/babel.

**Comment by tolyo** [comment]
@soumak77 Please give it a test drive.

**Comment by soumak77** [comment]
@tolyo base-apps-router has been updated to not require gulp.  Is there a way to run it with just babel/brunch so the gulp dependency can be removed?

@gakimball any suggestions on how to update the build to accomplish this?

**Comment by tolyo** [comment]
@soumak77 I thought it was a gulp task. Can we update the docs to reflect this?

**Comment by soumak77** [comment]
@tolyo changes were made by @gakimball the other day to allow running outside of gulp (https://github.com/base-apps/base-apps-router/commit/4cb5be0794c8abff390fba58a37021a7a136fb60)

I'll update the [base-apps-router](https://github.com/base-apps/base-apps-router) README to include a non-gulp example.

**Comment by soumak77** [comment]
template is ready to start using
